### ISSUE TITLE
Trying to get property 'depot' of non-object

### ISSUE THREAD

**Issue by atharalipk** [BernhardK91/laravel-dpd#10]
Hi,

I am getting this error in response

**Trying to get property 'depot' of non-object**

Any suggestion?

Regards

**Comment by BernhardK91** [comment]
Hello @atharalipk,

can you provide some code and more details for the error message? In which file and which line does the error occure.

Best Regards,
Bernhard

**Comment by atharalipk** [comment]
Hi @BernhardK91,

I am using the same code of dpdShipment but with our own auth credentials, I think it is throwing exception at DPDAuthorisation.

Trying to get property 'depot' of non-object {"userId":6,"exception":"[object] (ErrorException(code: 0): Trying to get property 'depot' of non-object at D:\\laragon\\www\\project\\vendor\\bernhardk\\laravel-dpd\\src\\DPDShipment.php:100) 

Regards,
Athar

**Comment by BernhardK91** [comment]
Please check the laravel logfile. Is there any entry that your credentials are invalid?
Do you have sandbox set to true or false in config/dpd.php?

**Comment by atharalipk** [comment]
I checked logfile but there is no invalid credentials entry.
yes sandbox is set to true in config but I am updating config on the fly which is also setting true, here is my authorization response
![image](https://user-images.githubusercontent.com/47610613/135454296-537d4bef-8a82-48b8-8198-4cf2afd053a8.png)

Actually I am not getting **token** data, I think this issue coming from DPD site because they are not returning token data

**Comment by BernhardK91** [comment]
Are you using production- oder demo-credentials?

**Comment by BernhardK91** [comment]
I have released an update that throws an exception if authorisation fails, because yesterday I got a strange error message when my credentials were wrong. 
Please checkout if that update helps.

**Comment by atharalipk** [comment]
I checked using both production and demo credentials but same error message.
Now I am getting "Invalid credentials..." message.
but I talk to support at Netherlands about my credentials, They reply its correct.
They gave me some other details but can't used like

DPD C number
DPD A number
Shipping depot

**Comment by BernhardK91** [comment]
Can you provide me demo credentials via E-Mail? mail@bernhard-kraemer.com

**Comment by BernhardK91** [comment]
As we found out DPD NL uses different API versions then DPD Germany. Therefore, DPD NL is unfortunately not currently supported.
