### ISSUE TITLE
Add Laravel support for 5.2

### ISSUE THREAD

**Issue by melchior985** [BernhardK91/laravel-dpd#4]
HI!, is not an issue is more a request. If you can add support for Laravel 5.2 and for Laravel 7?, I know is old, but that's the system we have here. Thanks!

**Comment by BernhardK91** [comment]
@melchior985 I will update the package in the next week.

**Comment by BernhardK91** [comment]
Sorry, that I was not able to release this earlier. I just released version 1.3.0 with support for Laravel 5.2 and Laravel 7. Support for Laravel 8 will follow soon.
